Develop
CristiMachine25/2-functions-front-back pull request #2
Opened 2023-06-08 11:46 UTC by CristiMachine25

2023-06-09 06:01 UTC, tdeleanu commented
@CristiMachine25 can you fix conflicts?

2023-06-09 06:04 UTC, tdeleanu commented
Please provide a description for this PR with what changed

2023-06-09 06:14 UTC, tdeleanu commented
Add me tdeleanu as a colaborator to this repo

2023-06-10 23:16 UTC, CristiMachine25 commented
Done

2023-06-11 11:56 UTC, tdeleanu commented
Since you modified the structure of the project does the readme change in any way?

2023-06-11 12:02 UTC, tdeleanu requested changes
Make sure you combine both functionalities in only one server app and update the readme.

2023-06-11 12:03 UTC, CristiMachine25 commented
> Since you modified the structure of the project does the readme change in any way?

Yes, it does change. There was an incompatibility between the two readme files, but it does change.

2023-06-11 12:13 UTC, CristiMachine25 commented
> Make sure you combine both functionalities in only one server app and update the readme.

They are combined in only one server app and also readme is updated. i'm not sure why you can't see it.

2023-06-12 19:27 UTC, tdeleanu commented
1. node modules bad in .gitignore since the installed items are not in the root folder
2. node modules should not be present in the folrder. check server
3. why is there a redundant combinedFunction in root when it should not be there

2023-06-13 14:18 UTC, CristiMachine25 commented
> 1. node modules bad in .gitignore since the installed items are not in the root folder
> 2. node modules should not be present in the folrder. check server
> 3. why is there a redundant combinedFunction in root when it should not be there

done

2025-08-26 13:04 UTC, merged